services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=secret_pass
      - DB_HOST=db
      - DB_NAME=tododb
      - FLASK_DEBUG=1
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    # Remove volume mount for backend source code to avoid conflicts with built image
    # volumes:
    #   - ./backend:/app

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"  # Map host port 3000 to container port 80 (nginx)
    depends_on:
      - backend

  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret_pass
      - POSTGRES_DB=tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
